name: Build Nugget

on:
  workflow_dispatch:
    inputs:
      build_for_linux:
        description: 'Build Linux'
        required: false
        default: true
        type: boolean

jobs:
  build-linux:
    if: ${{ github.event.inputs.build_for_linux == 'true' }}
    runs-on: ubuntu-24.04-arm   # Native aarch64 runner
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Build Linux
        run: python compile.py

      - name: Tar Nugget (Linux)
        run: |
          cd dist
          tar -cJf Nugget_Linux_aarch64.tar.xz Nugget

      - name: Upload TAR (Linux)
        uses: actions/upload-artifact@v5
        with:
          name: Nugget_Linux_aarch64
          path: dist/Nugget_Linux_aarch64.tar.xz
